language: generic

sudo: required

services:
- docker

install: true

stages:
- build-and-test

matrix:
  include:
    - stage: build-and-test
      env: fedora=rawhide
    - stage: build-and-test
      env: fedora=29
    - stage: build-and-test
      env: fedora=28
    - stage: build-and-test
      env: fedora=27

before_script:
- if test -n "$fedora" ; then sed -i "s#^FROM.*#FROM registry.fedoraproject.org/fedora:$fedora#" tests/Dockerfile ; fi

script:
- docker build -t rpm2swidtag -f tests/Dockerfile .
- docker run --name rpm2swidtag -d rpm2swidtag sleep 600
- docker exec rpm2swidtag make test
- docker exec rpm2swidtag /usr/bin/rpm2swidtag bash
- docker exec rpm2swidtag dnf rpm2swidtag enable-regen
- docker exec rpm2swidtag swidq -n bash | grep .
- if docker exec rpm2swidtag swidq -n zsh | grep . ; then exit 1 ; fi
- docker exec rpm2swidtag dnf install -y zsh
- docker exec rpm2swidtag swidq -n zsh | grep .
