version: 2.1
jobs:
  arm-container:
    parameters:
      os:
        type: string
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: sed -i "s#^FROM.*#FROM $( echo << parameters.os >> | sed 's#^fedora-#registry.fedoraproject.org/fedora:#; s#^centos-stream-#quay.io/centos/centos:stream#;' )#" tests/Dockerfile
      - run: docker build -t rpm2swidtag -f tests/Dockerfile .
      - run: docker run --name rpm2swidtag -d rpm2swidtag sleep 600
      - run: docker exec rpm2swidtag mkdir the-tests
      - run: docker exec rpm2swidtag cp -rp Makefile test.sh tests README.md the-tests/
      - run: docker exec rpm2swidtag make -C the-tests test TEST_INSTALLED=true
workflows:
  workflow:
    jobs:
      - arm-container:
          matrix:
            parameters:
              os: [ fedora-latest, centos-stream-9, centos-stream-8 ]
