version: 2.1
jobs:
  arm-container:
    parameters:
      os:
        type: string
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: sed -i "s#^FROM.*#FROM $( echo << parameters.os >> | sed 's#^fedora-#registry.fedoraproject.org/fedora:#; s#^centos-stream-#quay.io/centos/centos:stream#;' )#" tests/Dockerfile
      - run: docker build -t rpm2swidtag-source -f tests/Dockerfile .
      - run: docker run --name rpm2swidtag-build -d rpm2swidtag-source sleep 600
      - run: docker exec rpm2swidtag-build tests/build.sh
      - run: docker run --name rpm2swidtag-test -d rpm2swidtag-source sleep 600
      - run: docker exec rpm2swidtag-build ls dist | grep noarch.rpm | while read f ; do docker cp rpm2swidtag-build:/src/dist/$f . ; done
      - run: for f in *.noarch.rpm ; do docker cp $f rpm2swidtag-test:/src/ ; done
      - run: docker rm -f rpm2swidtag-build
      - run: docker exec rpm2swidtag-test bash -c 'dnf install -y *.noarch.rpm'
      - run: docker exec rpm2swidtag-test dnf install -y diffutils createrepo_c
      - run: docker exec -e TEST_INSTALLED=true rpm2swidtag-test ./test.sh
workflows:
  workflow:
    jobs:
      - arm-container:
          matrix:
            parameters:
              os: [ fedora-latest, centos-stream-9, centos-stream-8 ]
