name: test

on:
  push:

jobs:
  build:
    name: x86_64 container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir dir && chmod 0755 dir
      - run: podman build -t test -f Dockerfile .
